export enum UITypes {
    HANDLE_CRED_INPUT_BORDER = 'HANDLE_CRED_INPUT_BORDER',
    HANDLE_CRED_INPUT_FOCUS = 'HANDLE_CRED_INPUT_FOCUS'
}

export enum APITypes {
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER'
}