export enum UITypes {
    HANDLE_CRED_INPUT_BORDER = 'HANDLE_CRED_INPUT_BORDER',
    HANDLE_CRED_INPUT_FOCUS = 'HANDLE_CRED_INPUT_FOCUS',
    HANDLE_SIDEBAR = 'HANDLE_SIDEBAR'
}

export enum ChatTypes{
    HANDLE_ROOM = 'HANDLE_ROOM',
    HANDLE_RECIVER = 'HANDLE_RECIVER',
}

export enum APITypes {
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    GOOGLE_AUTH = 'GOOGLE_AUTH',
    LOGOUT = 'LOGOUT',
    IS_LOGGED = 'IS_LOGGED',
    GET_ROOMS = 'GET_ROOMS',
    GET_USER = 'GET_USER',
    UPDATE_USER = 'UPDATE_USER',
    GET_USERS = 'GET_USERS',
    CREATE_ROOM = 'CREATE_ROOM',
    GET_LAST_ROOMS = 'GET_LAST_ROOMS',
    GET_MESSAGES_FROM_ROOM = 'GET_MESSAGES_FROM_ROOM',
    GET_PRIVATE_MESSAGES = 'GET_PRIVATE_MESSAGES',
    SEND_MESSAGE_TO_ROOM = 'SEND_MESSAGE_TO_ROOM',
    SEND_PRIVATE_MESSAGE = 'SEND_PRIVATE_MESSAGE',
}