export enum UITypes {
    HANDLE_CRED_INPUT_BORDER = 'HANDLE_CRED_INPUT_BORDER',
    HANDLE_CRED_INPUT_FOCUS = 'HANDLE_CRED_INPUT_FOCUS'
}

export enum ChatTypes{
    HANDLE_ROOM = 'HANDLE_ROOM',
    HANDLE_RECIVER = 'HANDLE_RECIVER',
}

export enum APITypes {
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    GET_ROOMS = 'GET_ROOMS',
    GET_MESSAGES_FROM_ROOM = 'GET_MESSAGES_FROM_ROOM',
    GET_PRIVATE_MESSAGES = 'GET_PRIVATE_MESSAGES',
    SEND_MESSAGE_TO_ROOM = 'SEND_MESSAGE_TO_ROOM',
    SEND_PRIVATE_MESSAGE = 'SEND_PRIVATE_MESSAGE',
}