import { UITypes } from "../types"

interface HANDLE_CRED_INPUT_BORDER {
    type:UITypes.HANDLE_CRED_INPUT_BORDER
}

interface HANDLE_CRED_INPUT_FOCUS {
    type:UITypes.HANDLE_CRED_INPUT_FOCUS
}
interface HANDLE_SIDEBAR {
    type:UITypes.HANDLE_SIDEBAR
}


export type Action = HANDLE_CRED_INPUT_BORDER | HANDLE_CRED_INPUT_FOCUS | HANDLE_SIDEBAR